### ISSUE TITLE
Placeholder Color

### ISSUE THREAD

**Issue by bluelovers** [Gerschel/sd-web-ui-quickcss#27]
https://www.w3schools.com/howto/howto_css_placeholder.asp

**Comment by Nacurutu** [comment]
?

**Comment by bluelovers** [comment]
![image](https://user-images.githubusercontent.com/167966/224880065-f71a61dd-5725-4597-bec2-8b8d8c08348b.png)

**Comment by Nacurutu** [comment]
When the textbox is not focused, the text is clear.
