### ISSUE TITLE
set max height for extra networks

### ISSUE THREAD

**Issue by bluelovers** [Gerschel/sd-web-ui-quickcss#28]
https://github.com/AUTOMATIC1111/stable-diffusion-webui/pull/8205

**Comment by Nacurutu** [comment]
as Vladmandic commented there, please add a description. what its trying to do. leaving the templated as-is without any explanation is not going to help.

What your codes fixes, what issue do you have?

**Comment by bluelovers** [comment]
after

![ShareX_2023-03-17-13-22-01-484](https://user-images.githubusercontent.com/167966/225819743-ffb3f10d-9945-4c36-a040-d94d1951f0de.png)

before

![ShareX_2023-03-17-13-23-32-461](https://user-images.githubusercontent.com/167966/225819911-78481669-4513-4b93-ac65-e99460c2106c.jpg)

**Comment by Nacurutu** [comment]
Added..!
