### ISSUE TITLE
"sd-web-ui-quickcss" is not compatible with "PromptHub" extension

### ISSUE THREAD

**Issue by klossm** [Gerschel/sd-web-ui-quickcss#33]
"sd-web-ui-quickcss" is not compatible with "PromptHub" extension, when I don't install "sd-web-ui-quickcss ", "PromptHub" can be displayed normally

Here is the link to PromptHub, I like both extensions and hope they are compatible with each other
https://github.com/Zetaphor/PromptHub

**Comment by Nacurutu** [comment]
hi, can u take a screenshot of the issue?

also, this is in the PromptHub repo:

Note: This is broken with the latest release of Automatic1111 on March 25'th. This update broke a LOT of extensions. I'm working on a fix. [See this reddit post for more details](https://www.reddit.com/r/StableDiffusion/comments/121kqkd/psa_hold_up_with_updating_automatic1111_for_now/).

**Comment by klossm** [comment]
I didn't update Automatic1111's latest webui, because I know the new version has a lot of bugs, and the author of prompthub I asked him on reddit, and it seems that his side is not necessarily solved

There is a discussion at the bottom of this address, and I have posted a screenshot
https://www.reddit.com/r/StableDiffusion/comments/121beq9/prompthub_prompt_history_and_better_saved_prompt/

**Comment by klossm** [comment]
I didn't update Automatic1111's latest webui, because I know the new version has a lot of bugs, and the author of prompthub I asked him on reddit, and it seems that his side is not necessarily solved，Sorry to discuss these issues in here.Since I'm not a professional, I can't tell which extension is causing the problem.

There is a discussion at the bottom of this address, and I have posted a screenshot，ComfortableSun2096 is my username
https://www.reddit.com/r/StableDiffusion/comments/121beq9/prompthub_prompt_history_and_better_saved_prompt/

**Comment by Nacurutu** [comment]
from our side, we just mess with the colors and the extra networks, we don't mess with the position of things.. however, let me update to the latest commit in a different folder and try both extensions to check for possible bugs.

Thank you

**Comment by klossm** [comment]
I seem to have found the problem, if I set the webui bat startup file toCOMMANDLINE_ARGS=--theme=darkblack theme, PromptHub does not display properly even if I do not install the extension sd-web-ui-quickcss.

In the case that sd-web-ui-quickcss and PromptHub are installed at the same time, if the --theme=dark parameter is removed, it can be displayed normally, so it is caused by the --theme=dark parameter.

So it's possible that PromptHub is having compatibility issues with the --theme=darkblack parameter

Sorry for bringing so many problems, thank you for your help，Thank you

**Comment by Nacurutu** [comment]
> I seem to have found the problem, if I set the webui bat startup file toCOMMANDLINE_ARGS=--theme=darkblack theme, PromptHub does not display properly even if I do not install the extension sd-web-ui-quickcss.
> 
> In the case that sd-web-ui-quickcss and PromptHub are installed at the same time, if the --theme=dark parameter is removed, it can be displayed normally, so it is caused by the --theme=dark parameter.
> 
> So it's possible that PromptHub is having compatibility issues with the --theme=darkblack parameter
> 
> Sorry for bringing so many problems, thank you for your help，Thank you

no worries, thank u for letting us know... as the last updates of the webUI brought too many issues, Im still waiting for a more stable commit to start looking for possible bugs
