### ISSUE TITLE
Can't find favicon.svg even though it's there

### ISSUE THREAD

**Issue by applesugarai** [Gerschel/sd-web-ui-quickcss#39]
I have a favicon.svg in the right spot but it fails to find it.

![screenshot 1681231396](https://user-images.githubusercontent.com/129874679/231231756-af30cf13-6b28-46bc-a50d-f1de1171c2b8.png)

`RuntimeError: File at path
F:\SD\stable-diffusion-webui\extensions\sd-web-ui-quickcss\file=static\favicon.svg does not exist.`

![image](https://user-images.githubusercontent.com/129874679/231236480-77a74dca-b1cb-40bf-84e0-51e8dffea5de.png)

**Comment by applesugarai** [comment]
Hmm. I restarted explorer.exe (I'm on Win11) and it seems to work now. I have no idea what happened. I'll try a couple more times to see if it happens again.

Edit: Ignore this. The issue still exists and the reason it didn't throw an error at me that time was because I didn't try to refresh A1111 in my browser.

**Comment by Nacurutu** [comment]
hehe, glad to read that is working now...
